#cloud-config

---
hostname: host1
coreos:
  etcd:
    discovery: https://discovery.etcd.io/74dc9ee6baba72a34504cb78db219f13
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4
  units:
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
  - name: docker-unrealircd.service
    command: start
    content: |
      [Unit]
      Description=Somehost IRC Server
      Author=Somehost Team
      After=docker.service

      [Service]
      Restart=always
      ExecStart=/usr/bin/docker run \
        -v /home/core/unrealircd/:/etc/unrealircd/ \
        -p 6697:6697 \
        -p 7000:7000 \
        --rm \
        --name="ircd" \
        hashbangsh/unrealircd
      ExecStop=/usr/bin/docker stop ircd
